name    'puppet-murmur'
version '0.0.1'
source 'UNKNOWN'
author 'tronpaul'
license 'Custom'
summary 'Voice chat server software'
description 'see mumble.sourceforge.net for details of the software'
project_page 'mumble.sourceforge.net'
